name: Build libplacebo

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  release:
    types: [ created ]

permissions:
  contents: write
  actions: read

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        include:
          - os: ubuntu-latest
            artifact_name: libplacebo-linux
            setup_deps: |
              sudo apt-get update
              sudo apt-get install -y ninja-build pkg-config \
                libvulkan-dev vulkan-utility-libraries-dev spirv-tools \
                glslang-tools spirv-cross \
                liblcms2-dev libxxhash-dev libunwind-dev
              curl -LsSf https://astral.sh/uv/install.sh | sh
              source ~/.cargo/env
          - os: windows-latest
            artifact_name: libplacebo-windows
            setup_deps: |
              # Use GitHub Actions pre-installed tools where possible
              # Python3, Git, CMake are already available
              
              # Install uv
              powershell -c "irm https://astral.sh/uv/install.ps1 | iex"
              
              # Install ninja via pip (more reliable than choco)
              pip install ninja
              
              # Install additional dependencies via vcpkg to match Linux feature set
              git clone https://github.com/Microsoft/vcpkg.git
              cd vcpkg
              ./bootstrap-vcpkg.bat
              ./vcpkg.exe install lcms:x64-windows xxhash:x64-windows
              cd ..
              
              # Set environment for vcpkg
              echo "CMAKE_TOOLCHAIN_FILE=$PWD/vcpkg/scripts/buildsystems/vcpkg.cmake" >> $GITHUB_ENV
              echo "VCPKG_ROOT=$PWD/vcpkg" >> $GITHUB_ENV
              
              # Skip Vulkan SDK - libplacebo wrap now includes Vulkan-Headers submodule
              echo "Using libplacebo's bundled Vulkan headers + vcpkg dependencies"

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Setup dependencies
      shell: bash
      run: ${{ matrix.setup_deps }}

    - name: Install Python dependencies
      run: uv sync

    - name: Setup build directory
      run: |
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          uv run meson setup builddir --default-library=shared --cmake-prefix-path="$VCPKG_ROOT/installed/x64-windows"
        else
          uv run meson setup builddir --default-library=shared
        fi
      shell: bash

    - name: Compile  
      run: uv run meson compile -C builddir

    - name: Test
      run: uv run meson test -C builddir -v

    - name: Install
      run: uv run meson install -C builddir --destdir=install

    - name: Package development files
      run: |
        # Create development package structure
        mkdir -p dev-package/lib dev-package/include dev-package/docs
        
        # Copy libraries
        if [ "${{ matrix.os }}" = "windows-latest" ]; then
          find builddir/subprojects/libplacebo/src -name "*.dll" -exec cp {} dev-package/lib/ \; 2>/dev/null || true
          find builddir/subprojects/libplacebo/src -name "*.lib" -exec cp {} dev-package/lib/ \; 2>/dev/null || true
          find builddir/subprojects/libplacebo/src -name "*.pdb" -exec cp {} dev-package/lib/ \; 2>/dev/null || true
        else
          find builddir/subprojects/libplacebo/src -name "*.so*" -exec cp {} dev-package/lib/ \; 2>/dev/null || true
        fi
        
        # Copy headers
        if [ -d "subprojects/libplacebo/src/include" ]; then
          cp -r subprojects/libplacebo/src/include/* dev-package/include/ 2>/dev/null || true
        fi
        
        # Copy config files - check multiple possible locations
        config_copied=false
        for config_path in \
          "builddir/subprojects/libplacebo/src/config.h" \
          "builddir/subprojects/libplacebo/config.h" \
          "subprojects/libplacebo/src/config.h" \
          "subprojects/libplacebo/config.h"; do
          if [ -f "$config_path" ]; then
            cp "$config_path" dev-package/include/
            config_copied=true
            echo "Found and copied config.h from: $config_path"
            break
          fi
        done
        
        # Copy config.h.in template if available
        if [ -f "subprojects/libplacebo/src/config.h.in" ]; then
          cp subprojects/libplacebo/src/config.h.in dev-package/include/ 2>/dev/null || true
        fi
        
        # FAIL if config.h was not found - we need to know about this!
        if [ "$config_copied" = "false" ]; then
          echo "ERROR: config.h not found in any expected location!"
          echo "Searched locations:"
          echo "  - builddir/subprojects/libplacebo/src/config.h"
          echo "  - builddir/subprojects/libplacebo/config.h" 
          echo "  - subprojects/libplacebo/src/config.h"
          echo "  - subprojects/libplacebo/config.h"
          echo ""
          echo "Build directory contents:"
          find builddir -name "config.h" -o -name "config.h.in" | head -10
          echo ""
          echo "Source directory contents:"
          find subprojects/libplacebo -name "config.h" -o -name "config.h.in" | head -10
          exit 1
        fi
        
        # Copy pkg-config file if it exists
        mkdir -p dev-package/lib/pkgconfig
        if [ -f "builddir/subprojects/libplacebo/libplacebo.pc" ]; then
          cp builddir/subprojects/libplacebo/libplacebo.pc dev-package/lib/pkgconfig/
        elif [ -f "builddir/subprojects/libplacebo/meson-uninstalled/libplacebo.pc" ]; then
          cp builddir/subprojects/libplacebo/meson-uninstalled/libplacebo.pc dev-package/lib/pkgconfig/
        fi
        
        # Copy documentation
        cp subprojects/libplacebo/README.md dev-package/docs/ || true
        cp subprojects/libplacebo/LICENSE dev-package/docs/ || true
        
        # Create comprehensive usage guide
        cat > dev-package/README.txt << 'EOF'
        libplacebo Development Package
        =============================
        
        Cross-platform GPU-accelerated video/image rendering library
        
        Directory Structure:
        - lib/          : Shared libraries (.so/.dll) and import libraries (.lib)
        - include/      : C/C++ header files
        - docs/         : Documentation and license
        - lib/pkgconfig/: pkg-config files for build systems
        
        Usage Examples:
        
        Linux (GCC):
        gcc -I./include -L./lib -lplacebo myapp.c
        
        Linux (pkg-config):
        gcc $(pkg-config --cflags --libs ./lib/pkgconfig/libplacebo.pc) myapp.c
        
        Windows (MSVC):
        cl /I.\include myapp.c .\lib\placebo.lib
        
        Windows (MinGW):
        gcc -I./include -L./lib -lplacebo myapp.c
        
        CMake Integration:
        find_library(PLACEBO_LIBRARY NAMES placebo PATHS ${CMAKE_CURRENT_SOURCE_DIR}/lib)
        target_include_directories(myapp PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/include)
        target_link_libraries(myapp ${PLACEBO_LIBRARY})
        
        Features Included:
        - Vulkan rendering backend
        - SPIR-V shader compilation
        - Advanced color processing
        - HDR tone mapping
        - Custom shader support
        
        For documentation visit: https://libplacebo.org/
        EOF
        
        # Create version info file
        echo "libplacebo $(cat subprojects/libplacebo/VERSION 2>/dev/null || echo 'unknown')" > dev-package/VERSION
        echo "Built on: $(date)" >> dev-package/VERSION
        echo "Platform: ${{ matrix.os }}" >> dev-package/VERSION
        echo "Architecture: x86_64" >> dev-package/VERSION
      shell: bash

    - name: Package artifacts (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: |
        cd dev-package
        zip -r ../${{ matrix.artifact_name }}.zip .

    - name: Package artifacts (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        cd dev-package
        7z a ../${{ matrix.artifact_name }}.zip .

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: ${{ matrix.artifact_name }}.zip

  auto-release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: Get short SHA
      id: sha
      run: echo "short_sha=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_OUTPUT
      
    - name: Create automatic release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: auto-${{ steps.sha.outputs.short_sha }}
        name: "Automatic Build ${{ steps.sha.outputs.short_sha }}"
        body: |
          **Automatic release from latest main branch**
          
          - Commit: ${{ github.sha }}
          - Author: ${{ github.actor }}
          - Vulkan-only libplacebo build
          - Cross-platform: Linux and Windows
          
          ## Download
          - **Linux**: libplacebo-linux.zip
          - **Windows**: libplacebo-windows.zip
          
          Both packages include:
          - Shared libraries (.so/.dll)
          - Header files for development
          - pkg-config files
          - Documentation
          
          Built with Meson + Vulkan support only.
        files: |
          libplacebo-linux/*.zip
          libplacebo-windows/*.zip
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: Upload to release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          libplacebo-linux/*.zip
          libplacebo-windows/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}